const mongoose= require('mongoose');
const userSchema = new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
       mobile:{
        type:String,
        required:true
    },
       role:{
        type:String,
        required:true
    },
       center:{
        type:String,
        required:true
    },
    qua:{
        type:String
    },
    skill:{
        type:String
    },
    exp:{
        type:String
    },
    add:{
        type:String
    },
    profilePic:{
        type:String
    },
    password:{
        type:String,
        default:"1234"
    },
    status:{
        type:String,
        default:"u"
    },
    otp:String,
    otpExpire:Date,
    otpVerified:{
      type:Boolean,
      default:false  
    }
},{
    timestamps:true
})

module.exports= mongoose.model("adduser",userSchema);